/* parts-spec.js — THE PARTS: the shape law, the alphabet and every environment piece of the COMIC 3D house style
 * 24 September 2026 (jumpr t36, the style book)
 *
 * Pure data, no Three.js, the environment counterpart of page-one-spec.js. The builders (kit/parts.js), the house
 * (kit/interior.js builds every prop from them), the parts box (parts.html) and the style book (style/book.html) all
 * read this file, so a piece's rules, its render and its card cannot drift apart.
 *
 * Every piece is built at its own origin: base on y = 0, front toward +z, centred on x. Where it rests in a scene (a
 * counter, a wall, a ceiling) is the scene's business: `rest` is the height it sits at when the scene names none.
 * Units: 1 u = 1 m.
 */

/* ───────────────────────── the shape law ───────────────────────── */
export const SHAPE_LAW = {
  scale: '1 u = 1 m (PAGE ONE: 1 u ≈ 4 cm; in a room the plane flies at 0.06)',
  // the facet ladder: a round thing gets its sides from its radius (m). Facets are the look: never smooth a curve past it.
  ladder: [[0.03, 6], [0.08, 8], [0.2, 12], [0.5, 16], [1.2, 24], [Infinity, 32]],
  ringFactor: 2,                       // around a ring (a torus's big circle): twice the ladder of its radius
  chamfer: { of: 0.12, max: 0.06 },    // soft goods: one chamfer facet, 12 % of the smallest dimension, at most 6 cm
  floor: 0.02,                         // under 2 cm across both thin directions: no ink hull (it would drown in its own line); a flat plate keeps its outline
  counts: { main: 1, secondary: 3, details: 5 },
  maxHues: 3,                          // per piece, besides stock, ink, steel and rubber
};
/** sidesFor(r): the facet ladder */
export function sidesFor(r) { for (const [rMax, n] of SHAPE_LAW.ladder) if (r <= rMax) return n; return 32; }

export const RULES = [
  { key: 'scale', name: 'Scale', rule: '1 u = 1 m. PAGE ONE is the one exception: 1 u ≈ 4 cm, flown at 0.06 in a room.' },
  { key: 'origin', name: 'Built at its own origin', rule: 'Base on y = 0, front toward +z, centred on x. The scene decides where a piece rests (a counter, a wall, a ceiling).' },
  { key: 'ladder', name: 'The facet ladder', rule: 'A round thing gets its sides from its radius: ≤ 3 cm 6 · ≤ 8 cm 8 · ≤ 20 cm 12 · ≤ 50 cm 16 · ≤ 1.2 m 24 · larger 32. Around a ring, twice the ladder. Never add sides to smooth a curve.' },
  { key: 'flat', name: 'Flat stays flat', rule: 'Folded, cut and built surfaces carry one normal per face. The realism dial rounds only what is round.' },
  { key: 'hardsoft', name: 'Hard and soft', rule: 'Hard goods (wood, metal, stone, walls) are sharp SLABs. Soft goods (upholstery, cushions, mats, washing) are CUSHIONs with one chamfer facet, 12 % of the smallest side, at most 6 cm. The chamfer catches the key as a highlight edge.' },
  { key: 'floor', name: 'The thickness floor', rule: 'Anything under 2 cm across in both of its thin directions (a cord, a wire, a grille bar, a clock hand) carries no ink hull; it would drown in its own line. A flat plate (a rug, a mat) keeps its outline. If a thin thing has to read, it is coloured ink.' },
  { key: 'counts', name: 'One, three, five', rule: 'One main mass, at most three secondary masses, at most five kinds of small detail. A repeat (doors in a run, rungs, slats) counts once. Clutter comes in odd counts, left-heavy.' },
  { key: 'silhouette', name: 'Silhouette first', rule: 'Every piece names the one cue its silhouette has to keep. Each family is rendered in solid ink to check it.' },
  { key: 'slots', name: 'Colour slots', rule: 'A piece names palette slots, never hexes: a body hue, the stock trim, steel, rubber, one accent. At most three hues besides stock, ink, steel and rubber. Shades only through shade() and mix().' },
  { key: 'ink', name: 'Ink by role', rule: 'Architecture 0.45, furniture 0.7, clutter 0.6, foliage 0.7, ground 0.35, light and marks 0, the hero 1.0. A landmark is its role × 1.25.' },
  { key: 'surfaces', name: 'Surfaces are line art', rule: 'Planks, pavers, terrazzo chips, grass ticks, panel mouldings, stripes: flat colour and ink line, never printed dots (the dots belong to the renderer).' },
  { key: 'marks', name: 'Marks, not materials', rule: 'Glass is two or three GLARE strokes. Light is an unlit GLOW with no ink. Wind and streams are DASHes. Steam is PUFFs on twos.' },
];

/* ───────────────────────── materials by role (ComicMaterial numbers) ───────────────────────── */
export const ROLES = {
  architecture: { ink: 0.45, mat: { hatch: 0.35, fillAmt: 0.25, keyMix: 0.25, bias: 0.3 }, what: 'walls, trim, casings: lit by the room (bias), never spot black' },
  ceiling:      { ink: 0.45, mat: { hatch: 0.2, fillAmt: 0.25, keyMix: 0.25, bias: 0.75 }, what: 'ceilings: the brightest bias' },
  floor:        { ink: 0.45, mat: { hatch: 0.3, fillAmt: 0.2, keyMix: 0.22 }, what: 'floors: a line texture, no hull' },
  furniture:    { ink: 0.7,  mat: { hatch: 0.6, fillAmt: 0.35 }, what: 'furniture and fixtures' },
  soft:         { ink: 0.7,  mat: { hatch: 0.3, fillAmt: 0.35, keyMix: 0.4 }, what: 'cushions, upholstery: a brighter key, lighter hatching' },
  metal:        { ink: 0.7,  mat: { hatch: 0.6, fillAmt: 0.35, spec: 1, gloss: 40, rim: 0.6 }, what: 'steel: one hard highlight dot and a rim' },
  gloss:        { ink: 0.7,  mat: { hatch: 0, fillAmt: 0.35, spec: 1, gloss: 70, rim: 0.8 }, what: 'black glass: spec and rim, no hatching' },
  clutter:      { ink: 0.6,  mat: { hatch: 0.5, fillAmt: 0.35 }, what: 'small things, rugs, mats' },
  foliage:      { ink: 0.7,  mat: { hatch: 0.5, fillAmt: 0.3, keyMix: 0.3 }, what: 'leaves, hedges, fronds' },
  ground:       { ink: 0.35, mat: { hatch: 0, fillAmt: 0.1, keyMix: 0.22 }, what: 'lawn, mulch, water: terrain weight' },
  light:        { ink: 0,    mat: { unlit: true }, what: 'glow shapes: light is never inked' },
  mark:         { ink: 0,    mat: { unlit: true }, what: 'glare, dashes, water: marks drawn on the page' },
  wrong:        { ink: 0.9,  mat: { hatch: 0.3, keyMix: 0.3, spec: 1, gloss: 40 }, what: 'the one wrong colour: heavy ink, a glint' },
  hero:         { ink: 1.0,  mat: { hatch: 1, fillAmt: 0.45, rim: 0.5, keyMix: 0.35 }, what: 'PAGE ONE only: one hero per frame' },
};
export const LANDMARK_MUL = 1.25;

/* ───────────────────────── the palette contract: pieces name slots, worlds fill them ───────────────────────── */
export const PALETTE_SLOTS = [
  { key: 'cyan', set: 'process', what: 'process cyan' },
  { key: 'magenta', set: 'process', what: 'process magenta' },
  { key: 'yellow', set: 'process', what: 'process yellow' },
  { key: 'paper', set: 'paper', what: 'interior walls' },
  { key: 'stock', set: 'paper', what: 'trim, ceilings, cushions, casings' },
  { key: 'ink', set: 'paper', what: 'the world\'s one ink, ink(the floor)' },
  { key: 'oak', set: 'ground', what: 'the floor wood; the ink derives from it' },
  { key: 'paver', set: 'ground', what: 'paving, terracotta' },
  { key: 'stucco', set: 'ground', what: 'the exterior walls' },
  { key: 'steel', set: 'neutral', what: 'metal' },
  { key: 'rubber', set: 'neutral', what: 'the darks: rubber, plinths, cords' },
  { key: 'lawn', set: 'nature', what: 'grass' },
  { key: 'hedge', set: 'nature', what: 'foliage' },
  { key: 'bark', set: 'nature', what: 'trunks (default: the floor wood, darker)' },
  { key: 'mulch', set: 'nature', what: 'beds (default: the floor wood, darkest)' },
  { key: 'cobalt', set: 'spot', what: 'spot hue' },
  { key: 'red', set: 'spot', what: 'spot hue' },
  { key: 'tangerine', set: 'spot', what: 'spot hue' },
  { key: 'teal', set: 'spot', what: 'spot hue' },
  { key: 'lime', set: 'wrong', what: 'THE wrong colour: one object per scene' },
  { key: 'counter', set: 'derived', what: 'terrazzo counters (default: the stock warmed with yellow)' },
  { key: 'glass', set: 'derived', what: 'black glass: oven doors, screens (default: the rubber, a touch lighter)' },
  { key: 'pond', set: 'derived', what: 'standing water (default: the cyan)' },
  { key: 'sky', set: 'derived', what: 'the far haze behind a treeline (default: the cyan half to white)' },
];

/* ───────────────────────── the alphabet ───────────────────────── */
export const ALPHABET = [
  { key: 'slab', name: 'SLAB', what: 'a box, sharp edges', used: 'walls, doors, counters, cabinets, shelves, table tops', rule: 'hard goods; per-face normals' },
  { key: 'cushion', name: 'CUSHION', what: 'a box with one chamfer facet', used: 'sofa, pillows, seat pads, mats, washing', rule: 'soft goods; chamfer 12 % of the smallest side, ≤ 6 cm' },
  { key: 'rod', name: 'ROD', what: 'a prism, sides by the ladder', used: 'legs, poles, posts, handles', rule: 'under 2 cm across: no hull' },
  { key: 'drum', name: 'DRUM', what: 'a frustum, sides by the ladder', used: 'pots, shades, round tops, rolls, cans', rule: 'sides from the larger radius' },
  { key: 'turned', name: 'TURNED', what: 'a lathe of up to six profile rows', used: 'kettles, bowls, baskets, vases, bells', rule: 'sides from the widest row' },
  { key: 'bent', name: 'BENT', what: 'a tube along a curve', used: 'faucets, trunks, frames, straps, cords', rule: 'round by the ladder of its radius' },
  { key: 'ring', name: 'RING', what: 'a torus, both ways by the ladder', used: 'fan guards, rims, handles', rule: 'around: twice the ladder of the big radius' },
  { key: 'shell', name: 'SHELL', what: 'an open cone or hood, two-sided', used: 'lamp shades, hoods, the egg chair', rule: 'the inside shows its own plane' },
  { key: 'puff', name: 'PUFF', what: 'a round lump: a sphere by the ladder, or an icosahedron for leaves and steam', used: 'knobs, kettlebells, pillows, birds, foliage, steam', rule: 'squash it; odd clusters, left-heavy; the dial may round it' },
  { key: 'crumple', name: 'CRUMPLE', what: 'a jittered icosahedron, flat facets', used: 'rocks, paper balls', rule: 'flat stays flat' },
  { key: 'cutout', name: 'CUTOUT', what: 'an extruded 2D outline', used: 'flat clouds, fronds, arches, signs, far skylines', rule: 'a few large authored arcs, no noise' },
  { key: 'sheet', name: 'SHEET', what: 'a folded card, PAGE ONE\'s own construction', used: 'the plane, washing, flags, paper signs', rule: 'a closed shell; folds ≥ 50° are inked' },
  { key: 'glare', name: 'GLARE', what: 'two or three white strokes', used: 'every pane of glass, a glossy box', rule: 'unlit, no ink; glass is never modelled' },
  { key: 'dash', name: 'DASH', what: 'an ink stroke', used: 'wind, streams, motion, fold lines', rule: 'unlit ink; steps on twos' },
  { key: 'glow', name: 'GLOW', what: 'an unlit light shape', used: 'bulbs, shades, lanterns, screens', rule: 'light is never inked' },
];

export const FAMILIES = [
  { key: 'structure', name: 'STRUCTURE', role: 'architecture 0.45', what: 'walls, openings, doors, stairs, porches, fences: the room itself' },
  { key: 'furniture', name: 'FURNITURE', role: 'furniture 0.7', what: 'what people sit on, store things in and cook on' },
  { key: 'fixtures', name: 'FIXTURES', role: 'furniture 0.7 · light 0', what: 'lights, fans, clocks, mirrors, taps, the washing line' },
  { key: 'clutter', name: 'CLUTTER', role: 'clutter 0.6', what: 'small things: odd counts, left-heavy, three clusters a room at most' },
  { key: 'nature', name: 'NATURE', role: 'foliage 0.7 · ground 0.35', what: 'plants, trees, rocks, water, sky, far rungs, a bird' },
  { key: 'effects', name: 'EFFECTS', role: 'marks 0', what: 'glare, dashes, puffs, arcs, glow: marks on the page' },
];

/* the catalogue cameras (yaw 0 = in front, at +z; el degrees above). Tiles scale every piece to one standard size. */
export const PART_VIEWS = {
  judge: { yaw: 32, el: 24, fov: 30, note: 'front-right, above: the model-sheet hero' },
  front: { yaw: 0, el: 6, fov: 24, note: 'the elevation' },
  side:  { yaw: 90, el: 6, fov: 24, note: 'from the right' },
  top:   { yaw: 0, el: 88, fov: 24, note: 'the plan' },
  under: { yaw: 25, el: -32, fov: 30, note: 'from below (ceilings)' },
};
export const TILE = { radius: 1.2, note: 'every tile scales its piece so the bounding sphere is 1.2 u; the ground grid scales with it and still reads true metres' };

/** where a kind rests when a scene gives no height (m): counters 0.92–0.94, the wall at 1.75, the ceiling at 2.7 */
export const REST = { sink: 0.94, faucet: 0.94, bowl: 0.94, dishRack: 0.94, paperTowel: 0.94, kettle: 0.94, breadBox: 0.92, bananas: 0.93, knifeBlock: 0.92,
  lantern: 1.75, clock: 1.75, pendant: 2.7, flushLight: 2.7 };

/* ───────────────────────── the pieces ─────────────────────────
 * kind: the builder in kit/parts.js · size [w, h, d] m · role (ink) · slots: palette keys by part · shapes: what it is made of
 * cue: the silhouette cue · moves: what steps on twos · from: where the house uses it (or 'new') · params: the catalogue's
 * instance · rest: the height it sits at when a scene names none · stub: 'wall' | 'counter' | 'ceiling' (catalogue context)
 * view: a tile camera other than judge · sub: the builder's own name when a card shows a variant */
export const PIECES = [
  /* STRUCTURE */
  { id: 'wall', kind: 'wall', name: 'WALL + BASEBOARD', family: 'structure', size: [3, 2.7, 0.12], role: 'architecture', slots: { body: 'paper', trim: 'stock' },
    shapes: 'SLAB 12 cm (the wall, merged) · SLAB 10 × 2 cm (the baseboard, on the viewer\'s side, broken at openings)', cue: 'a thick slab with a stock line at its foot', from: 'every room',
    params: { len: 3, h: 2.7, mat: 'paper' } },
  { id: 'wallDoor', kind: 'wall', name: 'WALL WITH A DOOR', family: 'structure', size: [3, 2.7, 0.12], role: 'architecture', slots: { body: 'paper', trim: 'stock', leaf: 'cobalt' },
    shapes: 'SLAB × 3 around the hole · SLAB × 3 (the casing, 7 cm) · the DOOR LEAF hung in it', cue: 'the casing frames a darker hole', from: 'foyer, kitchen',
    params: { len: 3, h: 2.7, mat: 'paper', openings: [{ at: 1.5, w: 0.95, h: 2.1, sill: 0, kind: 'door' }], leaf: { color: 'cobalt', open: 35 } } },
  { id: 'wallOpening', kind: 'wall', name: 'WALL WITH A CASED OPENING', family: 'structure', size: [3.4, 2.7, 0.12], role: 'architecture', slots: { body: 'cyan', trim: 'stock' },
    shapes: 'SLAB × 2 around the hole · SLAB × 3 (the casing)', cue: 'a wide doorway with no leaf: the next room shows through', from: 'foyer (the hall\'s mouth, the living room)',
    params: { len: 3.4, h: 2.7, mat: 'cyan', openings: [{ at: 1.7, w: 2.0, h: 2.2, sill: 0, kind: 'opening' }] } },
  { id: 'wallSlider', kind: 'wall', name: 'WALL WITH A SLIDER', family: 'structure', size: [4.6, 2.7, 0.12], role: 'architecture', slots: { body: 'paper', frame: 'stock' },
    shapes: 'SLAB wall · SLAB frame (6 cm) + mullion · GLARE × 3 on the closed pane · the open pane a gap', cue: 'one pane glinting, one pane open', from: 'the Pilates room',
    params: { len: 4.6, h: 2.7, mat: 'paper', openings: [{ at: 2.3, w: 3.2, h: 2.3, sill: 0, kind: 'slider', open: 'right' }] } },
  { id: 'wallWindow', kind: 'wall', name: 'WALL WITH A WINDOW', family: 'structure', size: [3, 2.7, 0.12], role: 'architecture', slots: { body: 'paper', frame: 'stock' },
    shapes: 'SLAB wall · SLAB frame · SLAB sill (proud 6 cm) · GLARE × 3', cue: 'a bright pane with a sill line under it', from: 'new',
    params: { len: 3, h: 2.7, mat: 'paper', openings: [{ at: 1.5, w: 1.2, h: 1.2, sill: 0.9, kind: 'window' }] } },
  { id: 'ceiling', kind: 'ceiling', name: 'CEILING', family: 'structure', size: [2.4, 0.06, 2.4], role: 'ceiling', slots: { body: 'stock' },
    shapes: 'SLAB 6 cm, bias +0.75, no hull (the walls ink its edges)', cue: 'the lightest plane in the room, gone when the camera is above it', from: 'every room',
    params: { w: 2.4, d: 2.4 }, view: 'under' },
  { id: 'door', kind: 'door', name: 'DOOR LEAF', family: 'structure', size: [0.95, 2.05, 0.04], role: 'furniture', slots: { body: 'cobalt', knob: 'steel' },
    shapes: 'SLAB leaf with the two-panel arched moulding (a line texture) · 2 knobs (8-sided)', cue: 'the arched top panel', from: 'foyer (cobalt), kitchen (teal)',
    params: { w: 0.95, color: 'cobalt' } },
  { id: 'stormDoor', kind: 'stormDoor', name: 'STORM DOOR', family: 'structure', size: [0.95, 2.05, 0.04], role: 'furniture', slots: { frame: 'cobalt', handle: 'steel' },
    shapes: 'SLAB frame × 4 + mid rail + kick plate · GLARE × 3 · a handle', cue: 'a frame around nothing but glare', moves: 'breathes ±3° on twos', from: 'foyer',
    params: { w: 0.95, color: 'cobalt' } },
  { id: 'stairs', kind: 'stairs', name: 'STAIRS', family: 'structure', size: [1.0, 1.26, 1.96], role: 'architecture', slots: { treads: 'oak', risers: 'stock' },
    shapes: 'SLAB × 7 treads (4 cm, nosing 2 cm) · SLAB × 7 risers · SLAB × 2 stringers', cue: 'the sawtooth of treads and risers, odd count', from: 'new',
    params: { w: 1.0, steps: 7, rise: 0.18, run: 0.28, color: 'oak' } },
  { id: 'screenCage', kind: 'screenCage', name: 'SCREEN PORCH', family: 'structure', size: [4.6, 2.6, 4.1], role: 'furniture', slots: { frame: 'stock' },
    shapes: 'ROD posts (6 cm square) · SLAB beams and kick rails · GLARE on every screened panel · the door leaf standing open', cue: 'a white cage of posts that glints', from: 'the lanai',
    params: { w: 4.6, d: 4.1, h: 2.6, doorAt: 0.575, doorW: 1.15 } },
  { id: 'fence', kind: 'fence', name: 'FENCE + GATE', family: 'structure', size: [7.2, 1.95, 0.2], role: 'furniture', slots: { body: 'stock' },
    shapes: 'ROD posts (13 cm square) every 2.4 m · SLAB panels 1.6 m · SLAB gate leaf, open', cue: 'a white picket rhythm broken by the open gate', from: 'the backyard',
    params: { w: 7.2, gateAt: 0, gateW: 1.2 } },

  /* FURNITURE */
  { id: 'sofa', kind: 'sofa', name: 'SOFA', family: 'furniture', size: [2.4, 1.02, 0.95], role: 'soft', slots: { body: 'red', pillows: 'yellow · stock · cyan' },
    shapes: 'CUSHION base · CUSHION back · CUSHION × 2 arms · CUSHION × 3 pillows (tilted 14°)', cue: 'arms higher than the seat, three pillows', from: 'the living room',
    params: { w: 2.4, d: 0.95, color: 'red' } },
  { id: 'baseRun', kind: 'baseRun', name: 'BASE CABINET RUN', family: 'furniture', size: [2.3, 0.92, 0.62], role: 'furniture', slots: { body: 'teal', plinth: 'rubber', handles: 'steel', top: 'terrazzo' },
    shapes: 'SLAB plinth · SLAB carcass · SLAB doors + drawers (shaker line art) in a repeat · steel pulls · SLAB terrazzo top', cue: 'a dark toe-kick, doors in a row, a pale top', from: 'the kitchen',
    params: { x: 0, w: 2.3, d: 0.62, color: 'teal' } },
  { id: 'upperRun', kind: 'upperRun', name: 'UPPER CABINETS', family: 'furniture', size: [2.65, 2.28, 0.34], role: 'furniture', slots: { body: 'teal', crown: 'stock', handles: 'steel' },
    shapes: 'SLAB carcass 1.42 → 2.28 m · SLAB doors (shaker) in a repeat · SLAB crown', cue: 'a band of doors under a stock crown', from: 'the kitchen', stub: 'wall',
    params: { x: 0, w: 2.65, d: 0.34, color: 'teal' } },
  { id: 'peninsula', kind: 'peninsula', name: 'PENINSULA', family: 'furniture', size: [2.6, 0.94, 1.0], role: 'furniture', slots: { body: 'teal', top: 'terrazzo' },
    shapes: 'SLAB plinth · SLAB body · SLAB doors + drawers in a repeat · SLAB top with a 30 cm overhang', cue: 'the overhang: a top wider than its body', from: 'the kitchen',
    params: { w: 2.6, d: 1.0, color: 'teal' } },
  { id: 'range', kind: 'range', name: 'RANGE', family: 'furniture', size: [0.76, 1.03, 0.66], role: 'metal', slots: { body: 'steel', glass: 'black glass', towel: 'runner' },
    shapes: 'SLAB steel body · SLAB black-glass door + GLARE · BENT handle bar · RING × 4 burners (glare) · a towel', cue: 'the black oven door with a glint', from: 'the kitchen (landmark)',
    params: { w: 0.76, d: 0.66 } },
  { id: 'microwave', kind: 'microwave', name: 'MICROWAVE', family: 'furniture', size: [0.76, 0.42, 0.4], role: 'metal', slots: { body: 'steel', glass: 'black glass' },
    shapes: 'SLAB steel box · SLAB × 2 black glass (door, keypad) · GLARE', cue: 'a wide window and a narrow keypad', from: 'the kitchen (landmark, over the range)',
    params: { w: 0.76, d: 0.4 } },
  { id: 'reformer', kind: 'reformer', name: 'REFORMER', family: 'furniture', size: [0.68, 0.7, 2.45], role: 'furniture', slots: { frame: 'yellow', pads: 'stock', straps: 'cyan', metal: 'steel' },
    shapes: 'SLAB rails + ends + legs · CUSHION carriage + headrest · DRUM shoulder blocks · ROD springs · BENT foot bar · BENT straps', cue: 'a long low frame with a foot bar up at one end', from: 'the Pilates room (landmark)',
    params: { w: 0.68, d: 2.45, color: 'yellow' } },
  { id: 'eggChair', kind: 'eggChair', name: 'EGG CHAIR', family: 'furniture', size: [0.9, 1.35, 0.9], role: 'furniture', slots: { wicker: 'magenta', cushion: 'stock', legs: 'rubber' },
    shapes: 'TURNED bowl · SHELL hood (open at the front) · DRUM seat pad · PUFF back pillow · BENT × 4 legs; wicker is a stripe', cue: 'a hooded egg: open at the front only', from: 'the lanai',
    params: { color: 'magenta' } },
  { id: 'sideTable', kind: 'sideTable', name: 'SIDE TABLE', family: 'furniture', size: [0.46, 0.55, 0.46], role: 'furniture', slots: { body: 'cobalt', cup: 'yellow' },
    shapes: 'DRUM top · ROD stem · DRUM foot · TURNED cup', cue: 'a round top on one stem', from: 'the lanai',
    params: { color: 'cobalt' } },
  { id: 'plantStand', kind: 'plantStand', name: 'PLANT STAND', family: 'furniture', size: [0.6, 1.15, 0.4], role: 'furniture', slots: { frame: 'stock', pots: 'cyan · magenta · yellow' },
    shapes: 'SLAB × 3 stepped shelves · BENT × 2 legs · 7 potted PLANTs (odd, left-heavy)', cue: 'three steps of pots climbing back', from: 'the lanai',
    params: { w: 0.6 } },
  { id: 'shoeTower', kind: 'shoeTower', name: 'SHOE TOWER', family: 'furniture', size: [0.32, 1.45, 0.9], role: 'furniture', slots: { shelves: 'oak', posts: 'rubber', shoes: 'seven spot and process hues' },
    shapes: 'SLAB × 5 shelves · ROD × 4 posts · SNEAKER × 22 in a repeat', cue: 'a tall rack striped with coloured shoes', from: 'the hall',
    params: { w: 0.32, d: 0.9, h: 1.45, colors: ['cyan', 'magenta', 'yellow', 'red', 'tangerine', 'cobalt', 'stock'] } },
  { id: 'table', kind: 'table', name: 'TABLE', family: 'furniture', size: [1.6, 0.75, 0.9], role: 'furniture', slots: { body: 'oak' },
    shapes: 'SLAB top (5 cm) · SLAB × 4 square legs · SLAB apron', cue: 'a thick top on four square legs', from: 'new',
    params: { w: 1.6, d: 0.9, h: 0.75, color: 'oak' } },
  { id: 'chair', kind: 'chair', name: 'CHAIR', family: 'furniture', size: [0.46, 0.9, 0.5], role: 'furniture', slots: { body: 'teal', seat: 'stock' },
    shapes: 'CUSHION seat pad · SLAB seat · SLAB × 4 legs · SLAB × 2 back posts + 3 rails', cue: 'a back of three rails', from: 'new',
    params: { color: 'teal' } },
  { id: 'bookshelf', kind: 'bookshelf', name: 'BOOKSHELF', family: 'furniture', size: [0.9, 1.8, 0.32], role: 'furniture', slots: { carcass: 'stock', books: 'process + spot hues' },
    shapes: 'SLAB carcass (sides, top, plinth, back) · SLAB × 4 shelves · SLAB books in odd, left-heavy runs, one leaning', cue: 'a box of shelves with a skyline of spines', from: 'new',
    params: { w: 0.9, h: 1.8, d: 0.32 } },

  /* FIXTURES */
  { id: 'pendant', kind: 'pendant', name: 'PENDANT', family: 'fixtures', size: [0.26, 0.85, 0.26], role: 'furniture', slots: { shade: 'tangerine', cord: 'rubber', light: 'glow' },
    shapes: 'DRUM canopy · ROD cord (no hull) · SHELL cone shade · DRUM cap · GLOW disc', cue: 'a cone on a line', from: 'hall, living room, kitchen', stub: 'ceiling', rest: 2.7,
    params: { h: 0.85, color: 'tangerine' } },
  { id: 'flushLight', kind: 'flushLight', name: 'FLUSH LIGHT', family: 'fixtures', size: [0.36, 0.09, 0.36], role: 'light', slots: { light: 'glow', rim: 'stock' },
    shapes: 'GLOW drum · DRUM rim', cue: 'a bright lens on the ceiling', from: 'the entry', stub: 'ceiling', rest: 2.7, view: 'under',
    params: {} },
  { id: 'floorLamp', kind: 'floorLamp', name: 'FLOOR LAMP', family: 'fixtures', size: [0.38, 1.7, 0.38], role: 'furniture', slots: { body: 'cobalt', light: 'glow' },
    shapes: 'DRUM base · ROD pole · GLOW drum shade', cue: 'a glowing drum on a thin pole', from: 'the Pilates room',
    params: { color: 'cobalt' } },
  { id: 'lantern', kind: 'lantern', name: 'LANTERN', family: 'fixtures', size: [0.2, 0.4, 0.2], role: 'furniture', slots: { body: 'stock', light: 'glow' },
    shapes: 'SLAB box · GLOW box · DRUM (4-sided) cap', cue: 'a lit box with a pyramid cap', from: 'the front door', stub: 'wall', rest: 1.75,
    params: {} },
  { id: 'fan', kind: 'fan', name: 'DRUM FAN', family: 'fixtures', size: [0.8, 0.95, 0.4], role: 'furniture', slots: { body: 'red', grille: 'rubber', blades: 'steel' },
    shapes: 'RING guard · SHELL drum · DRUM motor · RING × 2 + SLAB × 4 grille (no hull) · SLAB × 3 blades · BENT × 2 legs', cue: 'a big ring on two bent legs', moves: 'blades turn on twos; its wind is dashes', from: 'the Pilates room',
    params: { color: 'red' } },
  { id: 'boxFan', kind: 'boxFan', name: 'BOX FAN', family: 'fixtures', size: [0.5, 0.58, 0.2], role: 'furniture', slots: { body: 'cyan', grille: 'stock · rubber' },
    shapes: 'SLAB box · SLAB grille panel · RING × 3 + SLAB × 4 grille (no hull) · SLAB knob', cue: 'a square with a target on its face', moves: 'its wind is dashes', from: 'the hall', turn: 180,
    params: { w: 0.5, h: 0.55, color: 'cyan' } },
  { id: 'clock', kind: 'clock', name: 'CLOCK', family: 'fixtures', size: [0.54, 0.54, 0.06], role: 'furniture', slots: { face: 'stock', rim: 'cyan', hands: 'rubber' },
    shapes: 'DRUM face · RING rim · SLAB × 2 hands (no hull)', cue: 'a ring with two hands', from: 'the kitchen', stub: 'wall', rest: 1.75, turn: -90,
    params: { color: 'cyan' } },
  { id: 'mirror', kind: 'mirror', name: 'ARCHED MIRROR', family: 'fixtures', size: [0.8, 1.8, 0.3], role: 'furniture', slots: { frame: 'stock', glass: 'mirror' },
    shapes: 'CUTOUT arched frame · CUTOUT glass · GLARE × 3, leaning 8°', cue: 'a tall arch, leaning', from: 'the Pilates room', stub: 'wall',
    params: {} },
  { id: 'sink', kind: 'sink', name: 'SINK + FAUCET', family: 'fixtures', size: [0.76, 0.34, 0.46], role: 'metal', slots: { basin: 'rubber', tap: 'steel' },
    shapes: 'SLAB basin (inset) · SLAB divider (no hull) · BENT faucet', cue: 'a dark rectangle and a hooked tap', from: 'the kitchen', stub: 'counter', rest: 0.94,
    params: { w: 0.76, d: 0.46, faucet: true } },
  { id: 'clothesline', kind: 'clothesline', name: 'WASHING LINE', family: 'fixtures', size: [4.4, 1.9, 0.5], role: 'furniture', slots: { posts: 'stock', washing: 'cyan · yellow · magenta' },
    shapes: 'ROD × 2 posts + SLAB crossbars · ROD line (no hull) · CUSHION washing × 3 with SLAB pegs', cue: 'two T posts and the colours between them', from: 'the backyard',
    params: { w: 4.4, h: 1.9, lineY: 1.6, items: [{ x: [-1.6, -0.9], y: 0.9, color: 'cyan' }, { x: [0.7, 1.2], y: 1.0, color: 'yellow' }, { x: [1.5, 2.05], y: 0.5, color: 'magenta' }] } },

  /* CLUTTER */
  { id: 'basket', kind: 'basket', name: 'BASKET', family: 'clutter', size: [0.48, 0.36, 0.48], role: 'clutter', slots: { body: 'yellow' },
    shapes: 'TURNED (4 rows), a weave stripe of its own darker shade', cue: 'a tub, slightly flared', from: 'the hall',
    params: { color: 'yellow' } },
  { id: 'bowl', kind: 'bowl', name: 'BOWL', family: 'clutter', size: [0.22, 0.11, 0.22], role: 'clutter', slots: { body: 'magenta' },
    shapes: 'TURNED (4 rows), glossy', cue: 'a wide shallow cup', from: 'the peninsula', stub: 'counter', rest: 0.94,
    params: { color: 'magenta' } },
  { id: 'kettle', kind: 'kettle', name: 'KETTLE', family: 'clutter', size: [0.26, 0.4, 0.2], role: 'wrong', slots: { body: 'lime (the wrong colour)', handle: 'rubber' },
    shapes: 'TURNED body · RING handle · DRUM spout · PUFF × 4 steam', cue: 'the pear body, the handle hoop, the spout', moves: 'steam puffs step on twos', from: 'the peninsula (the kitchen\'s wrong colour)', stub: 'counter', rest: 0.94,
    params: {} },
  { id: 'kettlebell', kind: 'kettlebell', name: 'KETTLEBELL', family: 'clutter', size: [0.22, 0.29, 0.22], role: 'wrong', slots: { body: 'lime (the wrong colour)' },
    shapes: 'a sphere (12-sided) · RING handle, half', cue: 'a ball with a handle', from: 'the front door (the foyer\'s wrong colour)',
    params: {} },
  { id: 'breadBox', kind: 'breadBox', name: 'BREAD BOX', family: 'clutter', size: [0.46, 0.26, 0.3], role: 'clutter', slots: { body: 'tangerine' },
    shapes: 'SLAB box · GLARE', cue: 'a glossy block', from: 'the kitchen counter', stub: 'counter', rest: 0.92,
    params: { w: 0.46, d: 0.3, color: 'tangerine' } },
  { id: 'bananas', kind: 'bananas', name: 'BANANAS', family: 'clutter', size: [0.34, 0.07, 0.16], role: 'clutter', slots: { body: 'yellow' },
    shapes: 'BENT × 5 (a hand, odd)', cue: 'a fan of curves', from: 'the kitchen counter', stub: 'counter', rest: 0.93,
    params: {} },
  { id: 'knifeBlock', kind: 'knifeBlock', name: 'KNIFE BLOCK', family: 'clutter', size: [0.14, 0.3, 0.22], role: 'clutter', slots: { body: 'oak', handles: 'rubber' },
    shapes: 'SLAB block, tilted · SLAB × 4 handles', cue: 'a leaning block with four black stubs', from: 'the kitchen counter', stub: 'counter', rest: 0.92,
    params: {} },
  { id: 'paperTowel', kind: 'paperTowel', name: 'PAPER TOWEL', family: 'clutter', size: [0.16, 0.34, 0.16], role: 'clutter', slots: { roll: 'stock', stand: 'steel' },
    shapes: 'DRUM base · DRUM roll · ROD spindle (no hull)', cue: 'a white drum on a spike', from: 'the peninsula', stub: 'counter', rest: 0.94,
    params: {} },
  { id: 'dishRack', kind: 'dishRack', name: 'DISH RACK', family: 'clutter', size: [0.46, 0.22, 0.34], role: 'clutter', slots: { rack: 'steel', plates: 'cyan · stock · magenta', cup: 'oak' },
    shapes: 'SLAB rack · DRUM × 3 plates, on edge · SLAB cup', cue: 'three discs standing in a tray', from: 'the kitchen counter', stub: 'counter', rest: 0.94,
    params: { w: 0.46, d: 0.34 } },
  { id: 'plant', kind: 'plant', name: 'POT PLANT', family: 'clutter', size: [0.4, 0.85, 0.4], role: 'clutter', slots: { pot: 'tangerine', leaves: 'hedge' },
    shapes: 'TURNED pot, glossy · PUFF × 7 leaves (stretched blades)', cue: 'a fan of blades out of a pot', from: 'the Pilates room, the plant stand',
    params: { color: 'tangerine' } },
  { id: 'mat', kind: 'mat', name: 'DOORMAT', family: 'clutter', size: [0.9, 0.02, 0.58], role: 'clutter', slots: { body: 'coir' },
    shapes: 'SLAB (1.5 cm, coir line art)', cue: 'a bordered rectangle on the floor', from: 'the front door, the lanai',
    params: { w: 0.9, d: 0.58 } },
  { id: 'rug', kind: 'rug', name: 'RUG', family: 'clutter', size: [2.6, 0.01, 1.8], role: 'clutter', slots: { body: 'stock', pattern: 'magenta · cyan · yellow' },
    shapes: 'SLAB (8 mm, the diamond rug line art)', cue: 'a border and six diamonds', from: 'the living room',
    params: { w: 2.6, d: 1.8 } },
  { id: 'runner', kind: 'rug', name: 'RUNNER', family: 'clutter', size: [0.62, 0.01, 1.1], role: 'clutter', slots: { stripes: 'cyan · stock · magenta · yellow' },
    shapes: 'SLAB (8 mm, the zigzag stripe line art)', cue: 'bands across a narrow strip', from: 'the kitchen',
    params: { w: 0.62, d: 1.1, pattern: 'runner' } },
  { id: 'sneaker', kind: 'sneaker', name: 'SNEAKER', family: 'clutter', size: [0.12, 0.1, 0.3], role: 'clutter', slots: { sole: 'stock', upper: 'a spot or process hue' },
    shapes: 'SLAB sole · PUFF upper (stretched 1.7 ×)', cue: 'a sole under a long bump', from: 'the shoe tower',
    params: { color: 'magenta' } },
  { id: 'leafBlower', kind: 'leafBlower', name: 'LEAF BLOWER', family: 'clutter', size: [0.6, 0.4, 0.45], role: 'clutter', slots: { body: 'tangerine', parts: 'rubber' },
    shapes: 'SLAB body · DRUM nozzle · DRUM intake · BENT handle · SLAB trigger', cue: 'a box with a long tapering nose', moves: 'its stream is dashes', from: 'the backyard',
    params: { color: 'tangerine' } },
  { id: 'sprinkler', kind: 'sprinkler', name: 'SPRINKLER', family: 'clutter', size: [2.4, 1.6, 0.8], role: 'wrong', slots: { head: 'lime (the wrong colour)', water: 'water' },
    shapes: 'ROD spike · SLAB head + DRUM hub · BENT × 9 water arcs + drops (marks, no hull)', cue: 'a fan of arcs over a small head', moves: 'the head rocks on twos', from: 'the backyard (its wrong colour)',
    params: { w: 2.4, h: 1.6 } },
  { id: 'ladder', kind: 'ladder', name: 'AGILITY LADDER', family: 'clutter', size: [3.2, 0.03, 0.45], role: 'wrong', slots: { body: 'lime (the wrong colour)' },
    shapes: 'SLAB × 2 rails · SLAB × 9 rungs, no hull (they would drown)', cue: 'a flat ladder on the floor', from: 'the Pilates room (its wrong colour)',
    params: { w: 3.2, d: 0.45 } },
  { id: 'crate', kind: 'crate', name: 'CRATE', family: 'clutter', size: [0.5, 0.35, 0.4], role: 'clutter', slots: { body: 'oak' },
    shapes: 'SLAB × 4 corner posts · SLAB slats × 3 a side (odd) · SLAB floor', cue: 'slats with gaps between them', from: 'new',
    params: { w: 0.5, h: 0.35, d: 0.4, color: 'oak' } },

  /* NATURE */
  { id: 'shrub', kind: 'shrub', name: 'SHRUB', family: 'nature', size: [1.1, 0.95, 0.8], role: 'foliage', slots: { leaves: 'hedge' },
    shapes: 'PUFF × 3 or 5 (odd), squashed 0.85', cue: 'a cluster of round lumps', from: 'the front, the lanai',
    params: {} },
  { id: 'hedge', kind: 'hedge', name: 'HEDGE', family: 'nature', size: [4, 1.0, 1.0], role: 'foliage', slots: { leaves: 'hedge' },
    shapes: 'SHRUB × n along a line, jittered', cue: 'a row of lumps', from: 'the backyard',
    params: { w: 4, count: 3 } },
  { id: 'oak', kind: 'oak', name: 'LIVE OAK', family: 'nature', size: [7, 7.3, 6], role: 'foliage', slots: { trunk: 'bark', leaves: 'hedge (darker)' },
    shapes: 'BENT trunk · BENT × 3 limbs · PUFF × 10 crown', cue: 'a wide flat-topped crown on a short trunk', from: 'the backyard',
    params: {} },
  { id: 'palms', kind: 'palms', name: 'PALMS', family: 'nature', size: [8, 12.4, 4], role: 'foliage', slots: { trunks: 'bark', fronds: 'hedge (lighter)' },
    shapes: 'BENT curved trunk · CUTOUT × 11 fronds · a crown ball; three of them, leaning', cue: 'three leaning stems with starburst crowns', moves: 'fronds sway on twos', from: 'the backyard (landmark)',
    params: {} },
  { id: 'rock', kind: 'rock', name: 'ROCKS', family: 'nature', size: [1.3, 0.55, 0.9], role: 'foliage', slots: { body: 'steel (warmed)' },
    shapes: 'CRUMPLE × 3 (odd, left-heavy), flat facets', cue: 'hard faceted lumps', from: 'new',
    params: {} },
  { id: 'pond', kind: 'pond', name: 'POND', family: 'nature', size: [4, 0.02, 2.4], role: 'ground', slots: { water: 'pond' },
    shapes: 'CUTOUT ellipse, flat · RING ripples (marks)', cue: 'a flat oval with ring marks', moves: 'ripples grow on twos', from: 'the backyard',
    params: { w: 4, d: 2.4 }, view: 'top' },
  { id: 'cloud', kind: 'cloud', name: 'CLOUD', family: 'nature', size: [30, 8, 0.8], role: 'foliage', slots: { body: 'stock' },
    shapes: 'CUTOUT: 3 to 5 half-discs on a flat base, 0.8 deep', cue: 'a cut-paper bump row with a flat bottom', moves: 'drifts on ones', from: 'every sky',
    params: {}, view: 'front' },
  { id: 'treeline', kind: 'treeline', name: 'FAR TREELINE', family: 'nature', size: [60, 8, 0], role: 'ground', slots: { body: 'hedge → horizon' },
    shapes: 'CUTOUT ridge, unlit, on a depth rung (no fog, no ink)', cue: 'a flat bumpy band between sky and land', from: 'the backyard horizon',
    params: {}, view: 'front' },
  { id: 'cardinal', kind: 'cardinal', name: 'CARDINAL', family: 'nature', size: [0.1, 0.18, 0.3], role: 'furniture', slots: { body: 'red', beak: 'tangerine' },
    shapes: 'PUFF body · PUFF head · DRUM crest · DRUM beak · SLAB tail', cue: 'the crest', moves: 'turns its head on twos', from: 'the washing line',
    params: {} },

  /* EFFECTS */
  { id: 'glare', kind: 'glarePane', name: 'GLARE', family: 'effects', size: [0.9, 1.2, 0.06], role: 'mark', slots: { strokes: 'white', frame: 'stock' },
    shapes: 'GLARE × 3 strokes (7 cm and 3.5 cm) at −35° across a framed pane', cue: 'the diagonal strokes', from: 'every window, door and glossy box',
    params: { w: 0.9, h: 1.2 } },
  { id: 'windDashes', kind: 'windBox', name: 'WIND DASHES', family: 'effects', size: [1.8, 1.6, 2.4], role: 'mark', slots: { dashes: 'ink' },
    shapes: 'DASH × 20–40 scrolling through the boost box along its direction', cue: 'parallel strokes', moves: 'step on twos', from: 'the fans, the leaf blower',
    params: { dir: [0, 0.12, -1], x: [-0.9, 0.9], y: [0.2, 1.8], z: [-2.4, 0] } },
  { id: 'steam', kind: 'steamPuffs', name: 'STEAM', family: 'effects', size: [0.3, 0.5, 0.2], role: 'mark', slots: { puffs: 'white' },
    shapes: 'PUFF × 4, growing as they rise', cue: 'a rising stack of lumps', moves: 'grow and climb on twos', from: 'the kettle',
    params: {} },
  { id: 'waterArcs', kind: 'waterArcs', name: 'WATER ARCS', family: 'effects', size: [2.4, 1.6, 0.6], role: 'mark', slots: { water: 'water' },
    shapes: 'BENT × 9 arcs + drops, unlit, no hull', cue: 'a fan of arcs drawn all at once', from: 'the sprinkler',
    params: { w: 2.4, h: 1.6 } },
  { id: 'glow', kind: 'glowSet', name: 'GLOW', family: 'effects', size: [0.9, 0.4, 0.3], role: 'light', slots: { light: 'glow' },
    shapes: 'GLOW disc, drum and box: unlit, never inked', cue: 'flat bright shapes with no line', from: 'every lamp',
    params: {} },
  { id: 'motionDashes', kind: 'motionDashes', name: 'MOTION DASHES', family: 'effects', size: [0.6, 0.3, 1.6], role: 'mark', slots: { dashes: 'ink' },
    shapes: 'DASH × 3 behind a moving tip, re-rolled on twos', cue: 'three ticks trailing a point', moves: 're-roll on twos', from: 'PAGE ONE\'s winglet tips',
    params: {} },
  { id: 'ripples', kind: 'ripples', name: 'RIPPLES', family: 'effects', size: [3, 0.02, 2], role: 'mark', slots: { rings: 'water' },
    shapes: 'RING arcs (open), flat on the water, unlit', cue: 'broken rings', moves: 'grow on twos', from: 'the pond',
    params: {}, view: 'top' },
];

/** the surfaces board: line textures, each shown on a 1 m tile */
export const SURFACES = [
  { key: 'oak', name: 'OAK PLANKS', what: '18 cm planks along z, staggered ends, grain strokes at 16 % ink' },
  { key: 'paver', name: 'PAVERS', what: 'running bond, 15 cm courses, five tones, grout lines at 28 % ink' },
  { key: 'terrazzo', name: 'TERRAZZO', what: 'stock warmed with yellow, chipped with the process set and ink' },
  { key: 'rubber', name: 'RUBBER', what: 'the dark with a 1 m seam grid' },
  { key: 'lawn', name: 'LAWN', what: 'grass ticks in two shades, leaning up' },
  { key: 'mulch', name: 'MULCH', what: 'scattered strokes in two shades' },
  { key: 'stucco', name: 'STUCCO', what: 'knock-down arcs at 13 % ink' },
  { key: 'shaker', name: 'SHAKER DOOR', what: 'a recessed panel: one 45 % line, one 16 %' },
  { key: 'drawer', name: 'DRAWER', what: 'one bordered panel' },
  { key: 'doorPanels', name: 'DOOR PANELS', what: 'the arched top panel and a square bottom one' },
  { key: 'coir', name: 'COIR', what: 'a border and four diamonds' },
  { key: 'rug', name: 'RUG', what: 'a double border and six diamonds in the process set' },
  { key: 'runner', name: 'RUNNER', what: 'sixteen bands and zigzags' },
  { key: 'wicker', name: 'WICKER', what: 'a stripe of the body\'s own lighter shade (a material, not a texture)' },
];
